---
# Setup LAMP Stack
-  hosts: "webhosts"
   become: true
   pre_tasks:
    - pause: seconds=30
    - name: Wait for connection
      wait_for_connection:
        timeout: 300
      ignore_errors: yes
   tasks:

      - name: Install tools for adding PPA repositories
        apt:
          name: software-properties-common
          state: latest
          
      - name: Update apt-get repo and cache
        apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
        ignore_errors: yes

      -  name: Install lamp stack
         apt:
            pkg:
              - apache2
              - php-dev 
              - mysql-client
            state: present
            update_cache: yes

      -  name: start apache server
         service: 
              name: apache2
              state: started
              enabled: yes

      -  name:  create target directory
         file: path=/var/www/html state=directory mode=0755
