---
# Setup LAMP dbserver
-  hosts: "dbhosts"
   become: true
   pre_tasks:
    - pause: seconds=5
    - name: Wait for connection
      wait_for_connection:
        timeout: 600
      ignore_errors: yes     
   tasks:
   
      -  name: Install os packages
         yum:
            name: 
              - java
              - wget
              - unzip
            state: present
            update_cache: yes

      -  name: Get Derby Trader Database 
         unarchive: 
           src: https://ibm.box.com/shared/static/4u0mmdq00u86t74syn325tls2dvukita.zip 
           dest: /opt
           remote_src: yes
     
      -  name: start derby-server
         command: cd  /opt/DerbyServer/bin; nohup /usr/bin/sh ./start.sh -h {{ ipdb }}  &

# Setup web servers
-  hosts: "webhosts"
   become: true
   pre_tasks:
    - pause: seconds=5
    - name: Wait for connection
      wait_for_connection:
        timeout: 600
      ignore_errors: yes
   tasks:
      
      -  name: Install OS packages
         ignore_errors: yes
         yum:
            name:
              - java
              - wget
              - unzip
            state: present
            update_cache: yes
            
          
      -  name: ip dbserver in host file
         lineinfile:
           path: /etc/hosts
           line: "{{ ipdb }}      dbserver"
           insertafter: EOF
         
      -  name: Get Trader App in OpenLiberty
         unarchive:
          src:  https://ibm.box.com/shared/static/yyj83dpfvhdltn7q5i95mls9mybj47ud.zip
          dest: /opt
          remote_src: yes
         
      -  name: start liberty server
         ignore_errors: yes
         command: /usr/bin/sh /opt/olp/bin/server start tradeLiteServer --clean
         
      -  name: sleep 30
         pause:
            seconds: 30
         
      -  name: start liberty server
         ignore_errors: yes
         command: /usr/bin/sh /opt/olp/bin/server start tradeLiteServer

