---
# Setup web servers
-  hosts: "webhosts"
   become: true
   pre_tasks:
    - pause: seconds=5
    - name: Wait for connection
      wait_for_connection:
        timeout: 600
      ignore_errors: yes
   tasks:
      
      -  name: Install OS packages
         ignore_errors: yes
         yum:
            name:
              - java
              - wget
            state: present
            update_cache: yes
            
          
      -  name: ip dbserver in config file
         copy:
           content: "{{ ipdb }} dbserver"
           dest: "/etc/hosts"
         
      -  name: Get Trader App in OpenLiberty
         command : wget https://ibm.box.com/s/yyj83dpfvhdltn7q5i95mls9mybj47ud -O /opt/trader.zip

      -  name: unzip distribution
         unarchive:
           src: /opt/trader.zip
           dest: /opt
         
      -  name: start liberty server
         ignore_errors: yes
         command: /opt/olp/bin/server start tradeLiteServer

# Setup LAMP dbserver
-  hosts: "dbhosts"
   become: true
   pre_tasks:
    - pause: seconds=5
    - name: Wait for connection
      wait_for_connection:
        timeout: 600
      ignore_errors: yes     
   tasks:
   
      -  name: Install os packages
         yum:
            name: 
              - java
              - wget
            state: present
            update_cache: yes

      -  name: Get Trader App in OpenLiberty
         command : wget https://ibm.box.com/s/4u0mmdq00u86t74syn325tls2dvukita -O /opt/derbyServer.zip

      -  name: unzip distribution
         unarchive:
           src: /opt/derbyServer.zip
           dest: /opt
     
      -  name: start derby-server
         command: /opt/DerbyServer/bin/start.sh


